"""phase2 initial schema

Mirrors the DDL in CLAUDE.md §3 exactly — the same statements applied
directly to the live Supabase project via the Supabase MCP `apply_migration`
tool (migration name: phase2_initial_schema). Hand-written rather than
autogenerated: this baseline is meant to be the literal, auditable copy of
what already exists in the real database, not a SQLAlchemy-model-derived
approximation of it.

Revision ID: 0d5aabb6a1bc
Revises:
Create Date: 2026-08-15 19:06:19.024914

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d5aabb6a1bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # 3.2 users
    op.execute("""
        CREATE TABLE users (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          clerk_id TEXT UNIQUE NOT NULL,
          email TEXT UNIQUE,
          name TEXT,
          avatar_url TEXT,
          plan TEXT DEFAULT 'free',
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_users_clerk_id ON users(clerk_id)")
    op.execute("CREATE INDEX idx_users_email ON users(email)")

    # 3.3 conversations
    op.execute("""
        CREATE TABLE conversations (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          title TEXT DEFAULT 'New Conversation',
          summary TEXT,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          last_message_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_conversations_user_id ON conversations(user_id)")
    op.execute("CREATE INDEX idx_conversations_updated_at ON conversations(updated_at DESC)")

    # 3.4 messages
    op.execute("""
        CREATE TABLE messages (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
          user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
          content TEXT NOT NULL,
          embedding VECTOR(384),
          emotional_tone TEXT,
          tokens_used INTEGER,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_messages_conversation_id ON messages(conversation_id)")
    op.execute("CREATE INDEX idx_messages_user_id ON messages(user_id)")
    op.execute("CREATE INDEX idx_messages_created_at ON messages(created_at DESC)")
    op.execute("CREATE INDEX idx_messages_embedding ON messages USING hnsw (embedding vector_cosine_ops)")

    # 3.5 user_facts
    op.execute("""
        CREATE TABLE user_facts (
          id BIGSERIAL PRIMARY KEY,
          user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          subject TEXT NOT NULL DEFAULT 'User',
          predicate TEXT NOT NULL,
          object TEXT NOT NULL,
          confidence FLOAT DEFAULT 1.0,
          is_active BOOLEAN DEFAULT TRUE,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
          archived_at TIMESTAMP WITH TIME ZONE,

          UNIQUE(user_id, subject, predicate, object)
        )
    """)
    op.execute("CREATE INDEX idx_user_facts_user_id ON user_facts(user_id)")
    op.execute("CREATE INDEX idx_user_facts_active ON user_facts(user_id) WHERE is_active = true")
    op.execute("CREATE INDEX idx_user_facts_predicate ON user_facts(predicate)")

    # 3.6 session_state
    op.execute("""
        CREATE TABLE session_state (
          conversation_id UUID PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE,
          user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          turn_count INTEGER DEFAULT 0,
          current_persona TEXT,
          pending_persona TEXT,
          last_3_messages JSONB,
          updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX idx_session_state_user_id ON session_state(user_id)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TABLE IF EXISTS session_state")
    op.execute("DROP TABLE IF EXISTS user_facts")
    op.execute("DROP TABLE IF EXISTS messages")
    op.execute("DROP TABLE IF EXISTS conversations")
    op.execute("DROP TABLE IF EXISTS users")
